### ISSUE TITLE
Update LICENSE

### ISSUE THREAD

**Issue by twebermartins** [eclipse-aas4j/aas4j#10]
The [LICENSE](https://github.com/eclipse-digitaltwin/aas4j/blob/main/LICENSE) should be updated:

- [x] Change old license of Plattform Industrie 4.0 documents -from CC BY-ND 3.0 DE to CC BY-3.0 (see [here for more details](reative Commons CC BY-ND 3.0 DE))

- [ ] Do we need the header with the copyright? This is stopping that GitHub automatic identifies the Open Source License used in this project

**Comment by FrankSchnicke** [comment]
What is the status of this?

**Comment by twebermartins** [comment]
ongoing, still need to talk to some experts to ensure we are doing the right thing
