### ISSUE TITLE
[Feature] Easy integration of AAS4J JSON Serializer into other projects

### ISSUE THREAD

**Issue by FrankSchnicke** [eclipse-aas4j/aas4j#107]
Right now, integrating the JSON serializer in regard to Metamodel objects that are neither an Environment nor Referable requires copy & paste of code, cf. [BaSyx integration with AAS4J](https://github.com/eclipse-basyx/basyx-java-server-sdk/blob/main/basyx.common/basyx.http/src/main/java/org/eclipse/digitaltwin/basyx/http/Aas4JHTTPSerializationExtension.java).

By adding a possibility in AAS4J to configure the Jackson2ObjectMapperBuilder similar to how BaSyx is doing it, we could circumvent any code duplication and increase the quality of life of our users (like https://github.com/eclipse-aas4j/aas4j/issues/97).

@mjacoby @arnoweiss @twebermartins what do you think?

If you see no drawbacks in this way, I can gladly contribute this code for the next milestone release.

**Comment by twebermartins** [comment]
Sounds good! Maybe you can just briefly show to us next meeting.

**Comment by HansG89** [comment]
`Jackson2ObjectMapperBuilder` will only work for Spring projects. What about other frameworks like Quarkus?
Wouldn't it be better to have a Ser/Des that extends the standard Jackson Ser/Des classes? This way one could easily integrate AAS4J by following the documentation withing the used framework. Another approach would be to provide the entire Serializer as a custom Jackson module. I would assume that you don't want to add dependencies to frameworks like spring or quarkus to aas4j, right?

e.g., [Quarkus docs](https://quarkus.io/guides/rest-json#json

**Comment by FrankSchnicke** [comment]
@HansG89 can you take a look at the PR https://github.com/eclipse-aas4j/aas4j/pull/198 and check if this fulfills your requirements in regard to a more easy integration?

**Comment by HansG89** [comment]
looks good for me!

**Comment by FrankSchnicke** [comment]
Included in latest release milestone-04.
