### ISSUE TITLE
[Enhancement] Remove RDF 

### ISSUE THREAD

**Issue by twebermartins** [eclipse-aas4j/aas4j#108]

**Comment by kenwenzel** [comment]
Why is removal of RDF-support an enhancement?

**Comment by mhrimaz** [comment]
Are there any serializer out there to convert AAS (XML or JSON) to RDF? or any serious ongoing project that I can contribute?
As far as I know, [python-basyx-sdk](https://github.com/eclipse-basyx/basyx-python-sdk/issues/79) is not going to provide it anytime soon.
The aas4j is also removing it.
