### ISSUE TITLE
No ReleaseCandidate Version in Package Path

### ISSUE THREAD

**Issue by sebbader-sap** [eclipse-aas4j/aas4j#11]
From #3:
Would it be possible to go for a package name only containing the target version (v3) and not also including the current working version (in this case rc02)? I don't see a benefit having the sub-package. 

Only the additional effort on the consumer side - when fetching a new version - to update all imports. Also when we come to v3 final, the rc-package will be removed and the build within consumer projects will fail.

_Originally posted by @Smudo99 in https://github.com/eclipse-digitaltwin/aas4j/pull/3#discussion_r909451254_

**Comment by sebbader-sap** [comment]
It's a design decision in my view, which we should decide on as early as possible. 

Pro ...v3.rc02...:
* possible to load the 3.0.RC02 library and a future 3.0 at the same time

Con:
* A lot (!) of classes need to be touched without functional changes
* all implementing applications need to touch all their import statements

**Comment by mjacoby** [comment]
This is related to our previuos discussion whether we want to support the usage of multiple versions of the model within the same application. 

I like this idea but maybe we are not considering all implications here, e.g. we would also need to have multiple "copies" of other components such as the de-/serializers as they will only work for a specific version of the model.
If we keep all the versions over time in the code base, the dependencies will become quite large over time.

Considering only final versions of the model an approach could be something like this

Release `vX.Y.Z` with namespace `...v3...` used for all components, i.e. `...v3.model....`, `...v3.dataformat.json...`, `...v3.validator...` etc.

Upon release of next final version v4 of specification
Release `v(X+1).Y.Z` with namespace `...v4...` used for all components, remove all `...v4...` namespaces

If an application wants to support v3 and v4 it can include dependencies with `vX.Y.Z` and `v(X+1).Y.Z`.
Downside would be that each time an application wants to upgrade to a new version of the model it has to update all imports. 

Still the question remains how to handle RC-versions...

**Comment by twebermartins** [comment]
Agree with the prosal. Here is a [draft](https://github.com/eclipse-digitaltwin/aas4j/blob/main/docs/adr/decision_records.md#handling-the-package-structures-of-aas4j) to document decisions.

**Comment by sebbader** [comment]
This commit has the change now in the code:
https://github.com/eclipse-digitaltwin/aas4j/commit/9c87ff166dc2097b6dbc6daf67cef36773af7539

**Comment by sebbader** [comment]
Let's keep this issue open until we merge the `update-to-rc02` branch.
