### ISSUE TITLE
UnitTests for SubmodelElementLists in the Serialisers

### ISSUE THREAD

**Issue by sebbader** [eclipse-aas4j/aas4j#13]
The change from SubmodelElementStruct back to SubmodelElementCollection resulted in a replacement of all SubmodelElementLists and SubmodelElementStructs to SubmodelElementCollections due to the conducted copy-replace activity. 

This leads to the current situation that the ordered nature of SubmodelElementLists is not tested in the UnitTests.

This issue is a reminder for us to add such tests as soon as the functional features of v3.0.RC02 have been implemented.

**Comment by mjacoby** [comment]
- added a test for empty SubmodelElementList
