### ISSUE TITLE
The DefaultSubmodel has not default kind INSTANCE

### ISSUE THREAD

**Issue by emildinchev** [eclipse-aas4j/aas4j#145]
When you create a ned DefaultSubmodel and call getKind() you will get null

**Comment by mjacoby** [comment]
@sebbader-sap This reminds me of the issue of setting default values for some properties as defined in the specification in the constructor which we discussed some time ago. I am quite sure you implemented this feature in the generator, however, the latest code generated does not seem to have this. 

Has this functionality somehow been lost or disabled?

**Comment by sebbader-sap** [comment]
indeed. Most likely because my branch with this feature in the generator faced a lot of problems with the latest metamodel version, so I went back to a later state.

**Comment by sebbader-sap** [comment]
Or I expect default information in the ontology, which I have added manually to the aas-specs ontology... Don't remember.

**Comment by sebbader-sap** [comment]
see https://github.com/sap-contributions/aas4j/pull/3

**Comment by FrankSchnicke** [comment]
Fixed with latest release milestone-04
