### ISSUE TITLE
Serialized AASX File not readable by the AASX-Package-Explorer

### ISSUE THREAD

**Issue by tiermo** [eclipse-aas4j/aas4j#158]
I am currently creating multiple aasx files with the aasx-Serializer for a University-Project. Creating of basic aasx-files works so far but i cant open them in the AASX-Package-Explorer due to different errors. 
One of them is : Der Teil-URI muss mit einem Schrägstrich beginning.
The other one is: Unable to find AASX origin.

Do you have any idea what the reason could be, or what i have to change? Or is it not possible to open the aasx files with the package explorer?

**Comment by FrankSchnicke** [comment]
Are you using the AASX Package Explorer in a version that is already supporting the V3 meta model?

**Comment by tiermo** [comment]
I didn't find out if the Version is supporting the V3 meta model. But I used two different versions: First the Version v2023-02-03 and lately the most recent version which was released on the first of August v2023-08-01.

**Comment by tiermo** [comment]
In the newer version i can create SubmodelElementLists.

**Comment by FrankSchnicke** [comment]
Thank you very much for providing examples. Can you link the version you're using of the AASX Package Explorer?

**Comment by tiermo** [comment]
I am using the release V3.0 which was published on the first of august but it was removed from the releases some days later. 
So I cant link the version but i upploaded it here, so you can download it there: [](https://drive.google.com/drive/folders/1bxcMy75gA2htYjy_x2MPvp-i6xCiO2ou?usp=drive_link)

But before the first of August i was using this release with which i got similar issues: 
[v2023-02-03.alpha](https://github.com/admin-shell-io/aasx-package-explorer/releases/tag/v2023-02-03.alpha)
But as you showed me the v2023-02-03 Version does not support the V3 metamodel.

**Comment by FrankSchnicke** [comment]
Due to security compliance reasons I won't be able to execute the AASX Package Explorer build that you have provided. Is it by any chance the one tagged [here](https://github.com/admin-shell-io/aasx-package-explorer/releases/tag/v2023-08-02.alpha)?

**Comment by tiermo** [comment]
I think its the Version v2023-08-01.alpha which is tagged [here](https://github.com/admin-shell-io/aasx-package-explorer/releases/tag/v2023-08-01.alpha).
Sorry that i did not provide it before, i didn't know that there where tagged versions.

**Comment by tiermo** [comment]
Have you found any reason yet why the Package Explorer cant load the file? Or is there a Version of the Package Explorer that can load the file?

**Comment by FrankSchnicke** [comment]
We did not continue on this task due to vacation-related absences. However, we will take a look at this in the coming week and come back to you.

**Comment by FrankSchnicke** [comment]
This is a bug in the AASX Package Explorer, see https://github.com/admin-shell-io/aasx-package-explorer/issues/654

**Comment by BirgitBoss** [comment]
This issue should be re-opened: see my comment in https://github.com/admin-shell-io/aasx-package-explorer/issues/654#issuecomment-1839183821:

In Part 5 Chapter 5.4 File Name Conventions it is stated that /aasx/ shall be the common prefix for all files containing aasx package specific information. So relative paths seem not be conformant to the specification Part 5 V3.0.

**Comment by FrankSchnicke** [comment]
Please see my response on https://github.com/admin-shell-io/aasx-package-explorer/issues/654

**Comment by BirgitBoss** [comment]
This is a circle: please see my respone on https://github.com/admin-shell-io/aasx-package-explorer/issues/654#issuecomment-1849477557
