### ISSUE TITLE
Prepare - CI / Release (Maven Central, …)

### ISSUE THREAD

**Issue by twebermartins** [eclipse-aas4j/aas4j#19]
Check with Eclipse Foundation about Jenkins / Maven Central...

- [x] groupID: org.eclipse.digitaltwin.aas4j ??
- [x] artifcatID: dataformat-parent ??

**Comment by twebermartins** [comment]
@mjacoby @alw-iwu @sebbader-sap - FYI only, there is some information already on convention of Eclipse Foundation for Maven Central 
https://www.eclipse.org/projects/handbook/#resources-maven

I will ask Wayne about our proposal above....

**Comment by twebermartins** [comment]
According to Wayne, our proposal seems reasonable. However, the groupID must be agreed upon the Eclipse Digital Twin TPL PMC. I will start the discussion to agree on a groupID and once we have it, we should be able to used it.

By the way, we will need the assistance of Eclipse webmasters so that we get the resources related to JIPP and Maven Central. The process is written down here: https://wiki.eclipse.org/IT_Infrastructure_Doc#Publish_to_Maven_Central

**Comment by twebermartins** [comment]
PMC of Eclipse Digital Twin TPL has chosen `org.eclipse.digitaltwin.{project_name}` as a `groupID`. 
Meaning, that we should use `org.eclipse.digitaltwin.aas4j` as `groupID`

**Comment by sebbader-sap** [comment]
I will introduce the groupId change soon, preferably after we have merged the different PRs to `upgrade-to-rc02`.

**Comment by twebermartins** [comment]
- [ ] We need to ping the Eclipse Foundation to enable SonarCube precondition for maven central release.
- [ ] Configure Jenkins instance
