### ISSUE TITLE
Explore if removing the XSI Schema Location from XML fixes AASX Package Explorer Issue

### ISSUE THREAD

**Issue by FrankSchnicke** [eclipse-aas4j/aas4j#194]
As discussed in the Committer meeting on 7.11., it is not possible to provide a permanent URL to the XSD document right now. Thus, a trivial fix for https://github.com/eclipse-aas4j/aas4j/issues/186 would be to completely remove the schema location attribute. 

However, it needs to be checked if this also fixes the issue with the AASX Package Explorer.

**Comment by sebbader-sap** [comment]
See my comment in the other issue: https://github.com/eclipse-aas4j/aas4j/issues/186#issuecomment-1803588259 
Given that I did not miss anything, removing the XSI Schema Location would not make any difference.
