### ISSUE TITLE
Prefix artifact names with "aas4j-"

### ISSUE THREAD

**Issue by FrankSchnicke** [eclipse-aas4j/aas4j#195]
As suggested by @in-fke, prefixing our artifacts with "aas4j-" would enable self-explaining names. In addition, this would follow the approach of, e.g., Spring, BaSyx, and other well known libraries.

However, this is change that will have implications on imported maven projects in IDEs and will make working with already existing PRs cumbersome. Thus, we decided in the committer meeting of the 7.11. to do this (i) either as the last step before a release or (ii) in sync with a change that would have the same implications anyways.

ToDos:
- [ ] Rename maven artifact Id with prefix
- [ ] Rename folders with prefix
- [ ] Adapt README

**Comment by twebermartins** [comment]
Shall be done after the big PR #161 has been merged
