### ISSUE TITLE
Proper Default Handling for HasKind/kind

### ISSUE THREAD

**Issue by sebbader** [eclipse-aas4j/aas4j#20]
Part 1 states that `HasKind/kind` has the default value `Instance`:
<img width="787" alt="image" src="https://user-images.githubusercontent.com/12392907/184890399-463d26c6-09a6-4cb8-a51a-4b4d987e04a1.png">

However, the current behaviour is that, for instance, a Submodel with no kind element returns `null` if executing `getKind()`.

Proposal for discussion (alternative#1):
Let's change the functionality for `getKind()` to something like `if (this.kind != null) { return this.kind } else { return ModelingKind.Intance }  `

pro:
* if the deserialised Submodel has no kind attribute, so has its serialised version (would be different if we initialise it with ModelingKind.Intance)
* no `null` value returned as the actual value **is not** `null`

con:
* customisation of the generator only for `HasKind` necessary

Alternative#2:
Initialise with `ModelingKind.Intance`

con:
* customisation of the generator only for `HasKind` necessary
* deserialisation-serialization cycle "creates" the `hasKind` attribute

Alternative#3:
leave it for the business logic to handle `kind = null`

pro:
* no custom adjustments in the generator

con:
* what if the business application developer is not aware of the default value?

**Comment by mjacoby** [comment]
Are you sure that with Alternative#1 serialization will not serialize the property? AFAIK e.g. Jackson Framework uses getters to access the object properties and therefore would probably serialize this as `kind = Instance`. 

**Alternative#4** would be to initialize it as in Alterantive#2 but only serialize it if it differs from the default value. 

If I remember correctly, default values are defined for multiple elements, so there might be benefit in adopting a generic pattern to deal with default values, define them in the underlying ontology and handle them in the generator.

**Comment by mjacoby** [comment]
I totally agree with that. However, I want to point out that keeping the exact document in all details upon a deserialize-serialize circle would require substantial changes/extensions to the model as it requires to track for each property (or at least the ones with default value) whether it was present in the original file and the using this information upon serialization.

To keep things simple I would propose to either serialize properties with default value only when the value is different from the default value (to keep serialized document as short as possible) or to always serialize them.
Personally, I would prefer the first approach, but would also be ok with the latter.
