### ISSUE TITLE
Wrong Relationship Type in *.rels

### ISSUE THREAD

**Issue by FrankSchnicke** [eclipse-aas4j/aas4j#202]
See https://github.com/admin-shell-io/aasx-package-explorer/issues/666.

I think this should be fixed backwards compatible to ensure we're not losing compatibility with old files created by a milestone release of AAS4J. What do you think @mjacoby, @twebermartins?

**Comment by mjacoby** [comment]
I'm not sure what the best solution would be in this case...on the one hand we are talking about milestone releases which I guess would in theory allow adding breaking changes. However, I agree that this will most likely cause problems and disappointment from the users that they no longer can load files create by the previous version.

Therefore, I see two potential approaches (if technically possible)

1. Keep backwards compatibility by supporting both `http://www.admin-shell.io/aasx/relationships` and ` http://admin-shell.io/aasx/relationships`. We should add a warning message when loading a file using the "old" URL that the file is not compliant to the standard and will no longer be supported with the next release. Also we should always save files using the correct URL.
2. Remove support for "old" URL. In this case we should a a big fat note in the release notes stating the problem. We should also provide some simple command line tool to fix existing AASX files and should link that tool in the release notes.

I am fine with any of these two approaches.

**Comment by FrankSchnicke** [comment]
I think approach 1) would be feasible with little effort. I can take a look at implementing this next week.

**Comment by twebermartins** [comment]
I would also keep backwards compatibility for now. The idea of warning users is a good idea. And I would always automatically convert to the format as described in the spec.
