### ISSUE TITLE
Thumbnail images are not properly referenced when writing AASX files

### ISSUE THREAD

**Issue by andreas-schilling** [eclipse-aas4j/aas4j#256]
Thumbnail images for AASX files are currently simply exported along with other files, but are not properly referenced according to the specification.
This results in the problem, that e.g. the AASX explorer won't display the thumbnail image.
The AASX file as such is not broken or does cause actual errors, but the thumbnail image is kind of dangling inside the AASX.

To be correctly embedded, the file would need to be referenced from the root package, using the `http://schemas.openxmlformats.org/package/2006/relationships/metadata/thumbnail` relationship type.

I locally tested a fix and would be happy to provide a PR for this.

**Comment by FrankSchnicke** [comment]
Thank you for bringing this to our attention. We would be very grateful if you would consider contributing a PR!
