### ISSUE TITLE
File paths are written to AASX with file:// URI scheme

### ISSUE THREAD

**Issue by andreas-schilling** [eclipse-aas4j/aas4j#258]
Files that are written when serializing to AASX have their file path entry written with the `file://` URI scheme, which breaks the ability to view the files using the AASX explorer, as it is an absolute file URI.
However, the file can't be written without the leading slash as well, because a part name has to start with a slash.
What is the exact reason, that files are converted to absolute file URIs during serialization? I can't think of any case where this would be correct in the context of an AASX, as the files are always within the archive and thus relative to the archive root (of course the AASX explorer could be changed to allow reading such URIs from the local archive root, but that sounds also not quite correct).

The code that performs the conversion is located here: https://github.com/eclipse-aas4j/aas4j/blob/main/dataformat-aasx/src/main/java/org/eclipse/digitaltwin/aas4j/v3/dataformat/aasx/AASXSerializer.java#L251

If the `file://` prefix is manually removed afterwards from the XML within the archive, accessing the file works.

**Comment by FrankSchnicke** [comment]
Thanks for pointing out this issue with viewing in the AASX Package Explorer. We will discuss internally and update the ticket afterwards.

**Comment by FrankSchnicke** [comment]
Would it be possible to double-check if your AASX now works correctly with the AASX Package Explorer by using the code of the attached PR?

**Comment by andreas-schilling** [comment]
It does 👍

**Comment by FrankSchnicke** [comment]
Perfect 👍  After review, it will be merged and included in the next release in the coming weeks.
