### ISSUE TITLE
Fix Logic for Screaming Snake Case during Enum Deserialization

### ISSUE THREAD

**Issue by sebbader-sap** [eclipse-aas4j/aas4j#26]
from [java-serializer#63](https://github.com/admin-shell-io/java-serializer/pull/63):
"There was a problem during Enum deserialization. The identifier type value "Irdi" or "Iri" or "IRI" was always converted to "I_R_I" but the enum value in IdentifierType is IRI or IRDI."

**Comment by FrankSchnicke** [comment]
Since IdentifierType does not exist anymore, this can be considered fixed
