### ISSUE TITLE
Add more Utility/Convenience Functions

### ISSUE THREAD

**Issue by sebbader** [eclipse-aas4j/aas4j#29]
As stated e.g. in https://github.com/admin-shell-io/java-model/issues/13, the creation process of AAS entities is still pretty cumbersome. We may can add more convenience functions into `dataformat-core`. Please make proposals.

**Comment by FrankSchnicke** [comment]
From my perspective, the following features would be great:

- A Submodel does only allow retrieval of SubmodelElements as List. It would be beneficial to enable retrieval by IdShort (and semanticId?).
- Automatic reference resolution on an AASEnvironment, i.e.., providing a Reference and returning the referenced Referable (if included in the AASEnvironment).

**Comment by FrankSchnicke** [comment]
A further topic I see as import is a sensible toString() method for the metamodel elements

**Comment by mjacoby** [comment]
- Create Reference from Referable
- Parse Reference from String
- Get Parent of Referable (optional)
- Deep cloning of elements (optional)

**Comment by twebermartins** [comment]
see also #171

**Comment by FrankSchnicke** [comment]
As discussed in the last PL/committer meeting, I will close this issue and create separate issues for the points for better traceability.

The following points were addressed in the meantime:
- Create Reference from Referable
- Parse Reference from String
- Automatic reference resolution on an AASEnvironment, i.e.., providing a Reference and returning the referenced Referable (if included in the AASEnvironment).
- Sensible toString() method

The following points have their own issues:
- Deep cloning of elements (optional): https://github.com/eclipse-aas4j/aas4j/issues/85
- Get Parent of Referable (optional): https://github.com/eclipse-aas4j/aas4j/issues/213
