### ISSUE TITLE
Incorrect modelType of "DigitalFile" and "PreviewFile"  in HandoverDocumentation Submodel template

### ISSUE THREAD

**Issue by OussemaRZ** [eclipse-aas4j/aas4j#309]
**in the specification we have :** 

![image](https://github.com/user-attachments/assets/886cf705-166e-40a7-958a-2f77fcf9f921)

 **however "DigitalFile" and "PreviewFile" are set as SubmodelElement collection in the Json template  :**

![image](https://github.com/user-attachments/assets/26af56b4-ed9b-4b8d-96f4-40de268a8cf0)

**Comment by twebermartins** [comment]
Thanks for reaching out. After discussing this issue, we concluded that this issue is rather an Submodel Template issue than a code issue. Thus, please, raise an issue in this [Github repository](https://github.com/admin-shell-io/submodel-templates/issues)
