### ISSUE TITLE
Fix XML Unit Tests

### ISSUE THREAD

**Issue by sebbader-sap** [eclipse-aas4j/aas4j#4]
The `dataformat-xml` module of the initial version (PR https://github.com/eclipse-digitaltwin/aas4j/pull/2) currently only builds because https://github.com/sebbader/aas4j/blob/c5964e81e87258e08a1c83b01edc1df30e60d2d2/dataformat-xml/pom.xml#L62 deactivates all tests. They fail due to the upgrade of the `model` to version 3.0.RC02. The code needs to be reviewed and the compared AAS XML files in the test/resources folder updated.

**Comment by sebbader-sap** [comment]
https://github.com/eclipse-digitaltwin/aas4j/tree/update-to-rc02-xml contains fixes for most XML serialisation problems. However, the UnitTests still throw an exception like this:

```
java.lang.AssertionError: 
Expected: In Source 'file:/Users/I562354/Documents/2_git/aas4j/dataformat-xml/src/test/resources/minimum.xml' Expected child '{https://admin-shell.io/aas/3/0/RC02}environment' but was 'null' - comparing <aas:environment...> at /environment[1] to <NULL>:
```

@FrankSchnicke can you please execute the XmlSerializerTest and see if you can fix this?

**Comment by FrankSchnicke** [comment]
Fixed and pushed
