### ISSUE TITLE
No packages exists

### ISSUE THREAD

**Issue by mhrimaz** [eclipse-aas4j/aas4j#44]
Hi,

I am trying to convert an .aasx (xml) file to json. However, there isn't any packages published in this new repository. Packages exist in the old repo `https://github.com/orgs/admin-shell-io/packages?repo_name=java-serializer`.

Also there is `env.GITHUB_REPOSITORY` parameter in pom.xml which is not filled properly and not documented.

**Comment by mjacoby** [comment]
This is correct, there are currently no releases for this repository.
We decided to not re-release the previous state (as developed under https://github.com/orgs/admin-shell-io). We are currently working on updating the library to meta model v3.0RC02 and are planning to release a beta/release-candidate version under Eclipse AAS4j this year.

**Comment by FrankSchnicke** [comment]
The milestone releases of AAS4J are now available on [Maven Central](https://search.maven.org/search?q=aas4j)
