### ISSUE TITLE
AssetAdministrationShellEnvironmentSerializer sets empty lists to null during XML serialization and breaks serialized Environment

### ISSUE THREAD

**Issue by andreas-schilling** [eclipse-aas4j/aas4j#59]
The `AssetAdministrationShellEnvironmentSerializer` has an side effect on the `Environment` that is being serialized and thus it is broken afterwards.
It's not possible to serialize it a second time, e.g. to write both XML and AASX files.

The problematic part of the code is the following (line 125ff):
```
private void writeWrappedArray(ToXmlGenerator xgen, QName wrapper, QName wrapped, List<?> list)
            throws IOException {
        // overwrite all empty list with null, as the schema does not allow empty XML lists
        for (Object obj : list) ReflectionHelper.setEmptyListsToNull(obj);
```

The comment explains the measure, however the serializer should handle this issue differently. If this is not possible it probably would be best to keep track of which fields have been replaced with `null` and revert the change afterwards.

**Comment by FrankSchnicke** [comment]
Thank you very much for pointing out this issue. We will tackle this after the Hannover Fair.

**Comment by FrankSchnicke** [comment]
A sensible fix requires most likely copy constructors, thus this ticket is dependent on https://github.com/eclipse-aas4j/aas4j/issues/85
