### ISSUE TITLE
Invalid XML-Serialization of Property:displayName

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-aas4j/aas4j#60]
When serializing a property with a displayName, the `<displayName> foobar <\displayName>` tag is missing. Example:

```xml
<aas:property>
          <category>VARIABLE</category>
          <idShort>capacityGroupId</idShort>
          <aas:description>
            <aas:langString>
              <aas:language>en</aas:language>
              <aas:text>The Capacity Group ID identifies the capacity group on a global level.</aas:text>
            </aas:langString>
          </aas:description>
          <kind>Template</kind>
          <semanticId>
            <aas:keys>
              <aas:key>
                <aas:type>ConceptDescription</aas:type>
                <aas:value>urn:bamm:io.catenax.capacity_group:1.0.0#capacityGroupId</aas:value>
              </aas:key>
            </aas:keys>
          </semanticId>
          <valueType>xs:string</valueType>
          <value>0157ba42-d2a8-4e28-8565-7b07830c1110</value>
          <aas:langString>                                        <!-- Error starts here-->
            <aas:language>en</aas:language>
            <aas:text>Capacity Group ID</aas:text>
          </aas:langString>                                       <!-- Error ends here-->
</aas:property>
```

As it should, this does not validate against the xsd indicating an error in the last section of the example. The whole environment as AAS-XML can be provided at request (Github doesn't allow to attach XML to tickets for whatever reason)

**Comment by bs-jokri** [comment]
The problem occurred when serializing an AAS model generated here
https://github.com/eclipse-esmf/esmf-sdk/pull/289/files#diff-6b09490fe60476049e02ca3f18aad2c53c1e0b5def0d537a069e6926731d37ca

The display name for properties is set in AspectModelAasVisitor.java line 287 and is done like that:

```
private org.eclipse.digitaltwin.aas4j.v3.model.Property mapToAasProperty( final Property property ) {
       return new DefaultProperty.Builder()
             .idShort( property.getName() )
...
             .displayName( map( property.getPreferredNames() ) )
...
             .build();
    }
```

**Comment by bs-jokri** [comment]
The problem might be around this line
https://github.com/eclipse-aas4j/aas4j/blob/25f88ee2e58a8690c3f25f59ec86e8392be90ab2/dataformat-xml/src/main/java/org/eclipse/digitaltwin/aas4j/v3/dataformat/xml/mixins/ReferableMixin.java#L46

as it handles displayName
