### ISSUE TITLE
Fix JSON Unit Tests

### ISSUE THREAD

**Issue by sebbader-sap** [eclipse-aas4j/aas4j#7]
The `dataformat-json` module of the initial version (PR https://github.com/eclipse-digitaltwin/aas4j/pull/2) currently passes only one of the created tests. The others fail due to the upgrade of the `model` to version 3.0.RC02. The code needs to be reviewed and the compared AAS JSON files in the test/resources folder updated.

**Comment by sebbader** [comment]
https://github.com/eclipse-digitaltwin/aas4j/commit/c116cf7d6b2355640975460697dd72f89545d6d9 contains corrected UnitTests for the JSON (De-)Serialiser.

I propose to keep this issue open until we merge the branch. What's your opinion @mjacoby & @twebermartins ?

**Comment by twebermartins** [comment]
> [c116cf7](https://github.com/eclipse-digitaltwin/aas4j/commit/c116cf7d6b2355640975460697dd72f89545d6d9) contains corrected UnitTests for the JSON (De-)Serialiser.
> 
> I propose to keep this issue open until we merge the branch. What's your opinion @mjacoby & @twebermartins ?

It is ok for me!

**Comment by mjacoby** [comment]
I agree

**Comment by mjacoby** [comment]
I just managed to look at the current state of the JSON unit tests in branch [RC02](https://github.com/eclipse-digitaltwin/aas4j/tree/update-to-rc02).

Before actually being able to work I have some very basic questions

1. There are review comments inside the source code (e.g. [here](https://github.com/eclipse-digitaltwin/aas4j/blob/89694e953e5dfeaf4b82233f4dffaae590f56068/dataformat-json/src/test/java/org/eclipse/aas4j/v3/dataformat/json/ReflectionAnnotationIntrospectorTest.java#L166). Why are comments inside the source code instead on Github as a review? How should I answer to these? In source code? How will this work if a lengthy discussion develops? @sebbader I think you made most of these
2. Where to find details on the actual JSON format for v3.0RC02 as it is no longer part of the specification? Is the JSON schema normative? Another link to additional information provided in RC02 seems to be down (https://github.com/admin-shell-io/aas-specs/tree/master/schemas/json%23json-mapping-rules).

**Comment by sebbader-sap** [comment]
Hi Michael,

1. No, better not answer in the code :-). They were more intended as reminders for me while going through the code. If they are wrong, delete them. If not, just create an issue or let's raise them here.

**Comment by sebbader-sap** [comment]
2. This link works for me https://github.com/admin-shell-io/aas-specs/tree/master/schemas/json#json-mapping-rules . However, the JSON Schema at https://github.com/admin-shell-io/aas-specs/tree/master/schemas/json or the one at https://github.com/admin-shell-io/aas-specs/tree/draft-V3RC02-schemas/schemas/json is *not yet normative* for us. There are still a few updates needed before they can be released.

I have updated https://github.com/eclipse-digitaltwin/aas4j/blob/89694e953e5dfeaf4b82233f4dffaae590f56068/dataformat-json/src/main/resources/aas.json already, which should be as close as possible to the JSON Schema that will be released officially for RC02.

**Comment by FrankSchnicke** [comment]
I started aligning the existing JSONs with the changes in the ground truth, see linked PR.

**Comment by sebbader-sap** [comment]
> I started aligning the existing JSONs with the changes in the ground truth, see linked PR.

I updated the model classes already while working on the XML serialiser. The classes are however "hidden" in this branch: https://github.com/eclipse-digitaltwin/aas4j/tree/update-to-rc02-xml
Not sure if we better finish the XML Serializer and Deserialiser first and then merge or extract the model classes and merge them now already.

**Comment by sebbader-sap** [comment]
They contain a remodelling of the DataSpecification properties, so most this will also affect JSON.
