### ISSUE TITLE
aas4j/dataformat-json/src/test/resources/Example-Full.json is invalid (duplicate keys)

### ISSUE THREAD

**Issue by hmrc87** [eclipse-aas4j/aas4j#84]
[aas4j](https://github.com/eclipse-aas4j/aas4j/tree/main)/[dataformat-json](https://github.com/eclipse-aas4j/aas4j/tree/main/dataformat-json)/[src](https://github.com/eclipse-aas4j/aas4j/tree/main/dataformat-json/src)/[test](https://github.com/eclipse-aas4j/aas4j/tree/main/dataformat-json/src/test)/[resources](https://github.com/eclipse-aas4j/aas4j/tree/main/dataformat-json/src/test/resources)
/Example-Full.json

 seems to be invalid JSON.

https://jsongrid.com/json-parser shows invalid duplicate keys for "category" e.g. in line 558

![image](https://user-images.githubusercontent.com/1226017/227927349-98961f63-df4e-4401-b84e-3a5b78d22d74.png)

**Comment by twebermartins** [comment]
Thanks @hmrc87 for raising this, @mjacoby could you please have a look at it?

**Comment by mjacoby** [comment]
His issue has been resolved in the latest release.
