### ISSUE TITLE
[Feature] Client for AAS HTTP APIs

### ISSUE THREAD

**Issue by kenwenzel** [eclipse-aas4j/aas4j#94]
AAS4J should provide a client for the AAS HTTP APIs according to Asset Administration Shell Specification - Part 2: API (pp. 118 ff.):
https://industrialdigitaltwin.org/en/wp-content/uploads/sites/2/2023/04/IDTA-01002-3-0_SpecificationAssetAdministrationShell_Part2_API.pdf

**Comment by FrankSchnicke** [comment]
Currently, the scope of AAS4J is limited to the DotAAS Part 1 document. Thus, if there is no change in scope, we won't provide a client.

However, Eclipse BaSyx Java V2 aims to provide a client for the HTTP/REST API in the coming future.

**Comment by kenwenzel** [comment]
If this is out of scope then I'm going to close the ticket. Any suggestions?

**Comment by twebermartins** [comment]
Thanks for suggesting it. But as mentioned by @FrankSchnicke the scope of AAS4J is on implementing the part 1 of the AAS specs (meta model). Thus, the API part is out of scope. There are other open source projects converting this part (BaSyX, AASX Server, IDTA AAS Cloud Repository). I would suggest closing this ticket.

**Comment by FrankSchnicke** [comment]
[Eclipse BaSyx](https://github.com/eclipse-basyx/basyx-java-server-sdk) is now providing a Client SDK. You can find them by looking in the various components folders, e.g., [AAS Repository Client](https://github.com/eclipse-basyx/basyx-java-server-sdk/tree/main/basyx.aasrepository/basyx.aasrepository-client). While the available client does not cover all endpoints at the moment, we are continuously extending it.
