### ISSUE TITLE
[Refactoring] Regenerate Classes from rdf/shacl

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-aas4j/aas4j#96]
There were some [updates in the schema](https://github.com/admin-shell-io/aas-specs/pull/264). They go beyond our [request](https://github.com/admin-shell-io/aas-specs/issues/263) and recur to the spelling as it was in V3RC02. When generating the new classes, this will break our serializers (i.e. `semanticId` instead of `semanticID`). That's not necessarily a problem, it will however require to adapt and see if the public API will change.

- [ ] Regenerate classes
- [ ] Adjust serializers

**Comment by sebbader-sap** [comment]
Assigning myself for `Regenerate classes`.
